### ISSUE TITLE
Any more docs about this testsuite?

### ISSUE THREAD

**Issue by horseFucker123** [google/packetdrill#47]
Hi,
   I'm new to this packetdrill testsuite,Follow the  README I ran it and some tests failed,
![image](https://user-images.githubusercontent.com/63891725/99476094-e0e10100-298a-11eb-956a-895d820e7066.png)
  I tried to ran the single failing  tests such as no-coalesce-large.pkt, I got this 
![image](https://user-images.githubusercontent.com/63891725/99476302-3d442080-298b-11eb-8572-5152e8f4f69f.png)
Fellow the failing message ,vim no-coalesce-large.pkt,the 30 line I got this but I cant understand what it means
![image](https://user-images.githubusercontent.com/63891725/99476441-885e3380-298b-11eb-9e19-16fa7823a45f.png)
So I wonderd if there are any other docs I can refer to learn about this testsuite?

**Comment by horseFucker123** [comment]
I found some papers，ignore it,tks

**Comment by Bubble-mt** [comment]
I met same errors with you while running testcases, how would you get over the errors?

**Comment by nealcardwell** [comment]
You would need to share more details before we can help answer this
question:

(1) what is your goal?

(2) what is the kernel version and OS distribution you are using?

(3) what are the exact command lines you executed and the exact errors you
see?

best,
neal

**Comment by Bubble-mt** [comment]
Hi Neal，

Thanks for your kindly reply.

 (1) I want to use packetdrill to test network protocol. The tool provides some default tcp testcases, but I'm not sure what the scripts doing, so I want to run the testcases firstly on my OS. 

(2) I used i4.19 kernel, OS distributions are x86_64 and arch64.  Maybe the kernel version is old, I would run the tool by using kernel 5.10. 
BTW, would packetdrill support python3? I found it cant used by python3.

(3) I executed command like below:
./packetdrill/run_all.py -S -l -L -v tcp/mtu_probe/basic-v4.pkt

Then I saw the errors.
<img width="704" alt="1632742652(1)" src="https://user-images.githubusercontent.com/72586297/134900883-0781eafe-c113-4e68-8096-5c8b8077b62e.png">

I'm not sure if the errors are network protocol's error or env caused, if I change the code line, the testcase would be executed passed. 
+0 > P. 3387:3987(600) ack 1
_change to_
+0 > . 3387:3987(600) ack 1 win 256
<img width="652" alt="1632742751(1)" src="https://user-images.githubusercontent.com/72586297/134901103-36717b7d-be6a-4ae2-9dcc-a81c628c100d.png">

thanks,
bubble

**Comment by nealcardwell** [comment]
It seems like the failure you are seeing is caused by a missing PSH bit in
the TCP header.

That is likely due to your Linux v4.19 kernel being old enough that it does
not have the following commit that was in Linux v5.4:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=051ba67447de1294aaacc59752a37f72091d15ed
tcp: force a PSH flag on TSO packets

The Linux kernel TCP stack behavior changes over time; the tests in the tip
of the packetdrill tree only try to track the latest net-next behavior.

I would recommend building a net-next kernel, or using the newest kernel
supported by your distribution.

best,
neal

ps: AFAIK packetdrill only works with python2.
