### ISSUE TITLE
ERROR in excute script,"lockall(MCL_CURRENT | MCL_FUTURE): Function not implemented"

### ISSUE THREAD

**Issue by Nu1i** [google/packetdrill#57]
When i excute script,it occur error."lockall(MCL_CURRENT | MCL_FUTURE): Function not implemented".
root@X:~# uname -a
Linux X 4.4.0-19041-Microsoft #1-Microsoft Fri Dec 06 14:06:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nealcardwell** [comment]
This seems to be due to Microsoft's WSL not supporting that function. This is not a targeted platform, but if you want to see this platform supported, please feel free to submit a patch that skips the lockall command in the WSL environment, based on the /proc/version file (e.g. https://github.com/Microsoft/WSL/issues/1090)
