### ISSUE TITLE
Mac-OS Compatibility Problem When running run_all.py

### ISSUE THREAD

**Issue by xzwDavid** [google/packetdrill#72]
Hi, I run virtual machine on my macos, and I use ubuntu20.04 with 5.40 kernel version.
However, something goes wrong with testfile.
<img width="882" alt="Screen Shot 2023-02-28 at 22 59 56" src="https://user-images.githubusercontent.com/96334838/221892325-c96d9fe0-c050-42ea-b091-74b1fa298b6d.png">

**Comment by nealcardwell** [comment]
I think you need to simply change your script to use "wscale 8" rather than "wscale 7" for the wscale option in that SYNACK packet.

Please note that all other tests in the Linux packetdrill tests cases expect wscale 8 for outgoing SYNACK packets:

$ find . -name '*pkt' | xargs egrep '> S[.] ' | grep 'wscale 8'  | wc -l
48
$ find . -name '*pkt' | xargs egrep '> S[.] ' | grep 'wscale 7'  | wc -l
0

Thanks!

**Comment by xzwDavid** [comment]
> I think you need to simply change your script to use "wscale 8" rather than "wscale 7" for the wscale option in that SYNACK packet.
> 
> Please note that all other tests in the Linux packetdrill tests cases expect wscale 8 for outgoing SYNACK packets:
> 
> $ find . -name '*pkt' | xargs egrep '> S[.] ' | grep 'wscale 8' | wc -l 48 $ find . -name '*pkt' | xargs egrep '> S[.] ' | grep 'wscale 7' | wc -l 0
> 
> Thanks!

Yeah, it works.
Thanks for your advice. It makes my day. : )
